runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html


# access the static resources in the root director

- url: /(.*)
  static_files: \1
  upload: (.*)
  
libraries:
- name: webapp2
  version: "2.5.1"
  
- name: jinja2
  version: latest  
